### ISSUE TITLE
Is This Project Dead?

### ISSUE THREAD

**Issue by ohenepee** [crystal-community/leveldb#10]
An old issue was opened as far back as January this year, not even a comment on the issue by the maintainers. 

Can't resolve 0.2.0 when installing with the README.md's instruction... if you happen to remove the version part you get this error for version 0.1.0

```
Error in src/testlevel.cr:4: while requiring "leveldb"

require "leveldb"
^

in lib/leveldb/src/leveldb.cr:1: while requiring "./leveldb/*"

require "./leveldb/*"
^

Syntax error in lib/leveldb/src/leveldb/db.cr:9: unexpected token: as

      @err_ptr = pointerof(@err_address) as Pointer(UInt64)
```

**Comment by veelenga** [comment]
It is maintained by the community but seems like there is no regular maintainer on this project. You can create a PR to fix both issues, I will be happy to review/merge it.

If you don't want/can't, i will take a look when having some free time.

**Comment by veelenga** [comment]
Solved

**Comment by ohenepee** [comment]
Yeah it works now... with a minor issue
