### ISSUE TITLE
Invalid Access To Memory

### ISSUE THREAD

**Issue by ohenepee** [crystal-community/leveldb#11]
After putting 60 entries into the database... every 20 entries have a different key schema, e.g.
1st 20: `"messages/year/month/index"`
2nd 20: `"locations/year/month/index"`
3rd 20: `"something/someone/anyone/index"`

When I use the iterator to seek out "messages"... I print out the messages keyed entries correctly and goes on to print the other entries which aren't related to messages... the whole time `iterator.valid?` happens to be true. After printing the said entries, it adds the following:
```
Invalid memory access (signal 11) at address 0x18
[0x430906] ???
[0x426280] __crystal_sigfault_handler +32
[0x7f13536a1390] ???
[0x7f1353e60184] ???
[0x7f1353e4750a] ???
[0x7f1353e39c3d] leveldb_iter_key +13
[0x40eef0] __crystal_main +15296
[0x411828] main +40
[0x7f1352c84830] __libc_start_main +240
[0x40b259] _start +41
[0x0] ???
```

This is the iterator part of my code
```
while iterator.valid?
  iterator.next
  puts "#{iterator.key} - #{iterator.value}"
end

iterator.destroy
```

**Comment by veelenga** [comment]
@ohenepee as far as i understand you need to move iterator to the next at the end of the loop. What's happening now:


```
x x x
^
iterator.valid? # => true
iterator.next # => moves to the second value
iterator.key # => second key

x x x
  ^
iterator.valid? # => true
iterator.next # => moves to the third value
iterator.key # => third key

x x x
    ^
iterator.valid? # => true
iterator.next # => moves to the invalid pointer
iterator.key # => Invalid memory access
```

**Comment by veelenga** [comment]
That's how leveldb works. Using a seek you find a start point for the iterator and it will iterate till the end (having the alphabetical order in mind).

So if you need to stop when the first key with a different prefix occurs, you can break a loop:

```crystal
iterator = LevelDB::Iterator.new(db)
iterator.seek("messages")

while iterator.valid?
  break unless iterator.key.starts_with?("messages")

  puts "#{iterator.key} - #{iterator.value}"
  iterator.next
end

iterator.destroy

```

Related reading: https://groups.google.com/forum/#!topic/leveldb/DRj0-t1hJ08

**Comment by ohenepee** [comment]
You couldn't be more helpful... thanks a lot and stay blessed!
